build_cloud: Ubuntu-OLL
image: Ubuntu

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

on_finish:
  - sh: mv $APPVEYOR_BUILD_FOLDER /home/oll/Documents

build_script:
  - sh: docker run -e GH_SSH_PRIVATE_KEY=$env:GH_SSH_PRIVATE_KEY oll/archive-automation

notifications:
  - provider: Slack
    incoming_webhook:
      # post to the fire channel
      secure: KUaR+KAqX1jU0LF7kRDKHHGEAoItFzIHSjcreyRvnrRGMiSObCLPipW6KJUwvpl7CEWa8PP2LPzgiQssPcUWLCzoIVY+NvucTI+1NJ0H7GM=
    on_build_success: false
